In [2]:
# 27
import numpy as np
arr = np.array([1,2,2,3,4,4,4,5])
unique,counts = np.unique(arr,return_counts=True)
print("Unique values:",unique,"\nCounts:",counts)

Unique values: [1 2 3 4 5] 
Counts: [1 2 1 3 1]


In [5]:
# 28
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 29
import numpy as np
arr = np.arange(5)
exp = np.exp(arr)
print(exp)

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [11]:
# 30
import numpy as np
matrix = np.arange(9).reshape(3,3)
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [15]:
# 31
import numpy as np
matrix = np.random.random((3,3))
matrix[matrix > 0.5] = 1
matrix[matrix <= 0.5] = 0
print(matrix)

[[0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]]


In [36]:
# 32
import numpy as np
arr = np.array([3,4,2,5,6,1])
print(arr[np.argsort(arr)[-2:]])


[5 6]


In [42]:
# 33
import numpy as np
matrix = np.random.random((4,3))
col_means = np.mean(matrix, axis=0)
print(col_means)

[0.64353345 0.34559176 0.44417395]


In [45]:
# 34
import numpy as np
matrix = np.arange(9).reshape(3,3)
norm = (matrix - np.mean(matrix, axis=0)) / np.std(matrix, axis=0)
print(norm)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [46]:
# 35
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])
conc = np.concatenate((ar1,ar2))
print(conc)


[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
# 36
import numpy as np
arr = np.random.random((3,3))
print(np.sort(arr,axis=1))

[[0.40073558 0.89324614 0.98620775]
 [0.00198324 0.05411505 0.96479099]
 [0.02839605 0.44184584 0.6326993 ]]


In [56]:
# 37
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 3, 4, 5])
mse = np.mean((arr1 - arr2) ** 2)
print(mse)

1.0


In [58]:
# 38
import numpy as np
arr = np.array([1,-1,2,-2,3,-3])
arr[arr<0] = 0
print(arr)

[1 0 2 0 3 0]


In [59]:
# 39
import numpy as np
arr = np.random.random(10)
percentile_5th = np.percentile(arr, 5)
percentile_95th = np.percentile(arr, 95)
print("5th Percentile:", percentile_5th)
print("95th Percentile:", percentile_95th)

5th Percentile: 0.10303829491340295
95th Percentile: 0.9141094225220091


In [60]:
# 40
import numpy as np
matrix = np.random.random((2, 2))
determinant = np.linalg.det(matrix)
print(determinant)

0.11331945848808701


In [61]:
import numpy as np
arr = np.array([1,2,3,4,5])
count = np.sum(arr > np.mean(arr))
print(count)

2


In [62]:
# 42
import numpy as np
arr = np.array([4, 9, 16, 25])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[2. 3. 4. 5.]


In [70]:
# 43
import numpy as np
matrix = np.arange(9).reshape((3,3))
matrix_sqrt = np.linalg.matrix_power(matrix, 2)
print(matrix_sqrt)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [71]:
# 44
import numpy as np
arr = np.array([1, 2, 3, 4], dtype=int)
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3. 4.]


In [75]:
import numpy as np
arr = np.array([1,-1,2,-2,3,-3])
arr[arr<0] = -arr[arr<0]
print(arr)

[1 1 2 2 3 3]


In [76]:
# 46
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 2, 8, 4, 5])
matching_indices = np.where(arr1 == arr2)
print(matching_indices)

(array([1, 3, 4], dtype=int64),)


In [77]:
# 47
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)
print(cumulative_sum)

[ 1  3  6 10 15]


In [78]:
# 48
import numpy as np
matrix = np.random.random((2, 2))
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-3.79494815  2.52884453]
 [ 5.94299263 -2.31188427]]


In [79]:
import numpy as np
arr = np.array([0,1,0,2,0,3,4,5]).reshape(2,4)
count = np.sum(arr != 0)
print(count)

5


In [80]:
import numpy as np
matrix = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])
matrix[np.isnan(matrix)] = 0
print(matrix)

[[1. 0. 3.]
 [4. 5. 0.]
 [7. 8. 9.]]


In [81]:
# 51
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
correlation_coefficient = np.corrcoef(arr1, arr2)[0, 1]
print(correlation_coefficient)

0.9999999999999999


In [82]:
# 52
import numpy as np
arr = np.array([1, 2, 3, 2, 4, 5, 1])
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5]


In [83]:
# 53
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
elementwise_product = np.multiply(arr1, arr2)
print(elementwise_product)

[ 4 10 18]


In [84]:
# 54
import numpy as np
matrix = np.random.random((4, 3))
column_stddev = np.std(matrix, axis=0)
print(column_stddev)

[0.13842234 0.22798778 0.14121476]


In [85]:
# 55
import numpy as np
matrix = np.random.random((3, 4))
threshold = 0.7
matrix[matrix > threshold] = threshold
print(matrix)

[[0.7        0.7        0.20596455 0.39426498]
 [0.44617637 0.7        0.01908151 0.6449416 ]
 [0.7        0.3407672  0.47981985 0.7       ]]


In [105]:
# 56
import numpy as np
matrix = np.random.random((5,5))
matrix[np.unravel_index(np.argmax(matrix), matrix.shape)] = -1
print(matrix)

[[ 0.80201447  0.83766679  0.66526897  0.85334244  0.73468442]
 [ 0.09781883  0.24540954  0.91375759  0.92025348  0.35397501]
 [ 0.61566071  0.22768804  0.26216898  0.70968794  0.28854078]
 [-1.          0.07158393  0.40906839  0.46269451  0.8932246 ]
 [ 0.66278063  0.47601365  0.11586269  0.86791705  0.88555241]]


In [106]:
# 57
import numpy as np
fahrenheit_temps = np.array([32, 68, 100, 212])
celsius_temps = (fahrenheit_temps - 32) * 5/9
print(celsius_temps)

[  0.          20.          37.77777778 100.        ]


In [107]:
# 58
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
outer_product = np.outer(arr1, arr2)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [108]:
# 59
import numpy as np
equidistant_arr = np.linspace(0, 1, 10)
print(equidistant_arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [109]:
# 60
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
cross_product = np.cross(arr1, arr2)
print(cross_product)

[-3  6 -3]


In [110]:
# 61
import numpy as np
matrix = np.random.random((3, 4))
percentiles_axis1 = np.percentile(matrix, 75, axis=1)
print(percentiles_axis1)

[0.26721296 0.45294321 0.5958965 ]


In [111]:
# 62
import numpy as np
arr = np.array([1, 2, 3, 4])
arr_with_border = np.pad(arr, (1, 1), mode='constant', constant_values=0)
print(arr_with_border)

[0 1 2 3 4 0]


In [112]:
# 63
import numpy as np
arr = np.array([1, 1, 2, 2, 2, 3, 3, 3, 3])
hist, bins = np.histogram(arr, bins=[1, 2, 3, 4])
print("Histogram:", hist)
print("Bin edges:", bins)

Histogram: [2 3 4]
Bin edges: [1 2 3 4]


In [115]:
# 64
import numpy as np
arr = np.random.random((3,3))
print(matrix / np.linalg.norm(matrix,axis=1,keepdims=True))

[[0.73175479 0.60048772 0.31369984 0.0744435 ]
 [0.85471686 0.30153068 0.3531581  0.23198642]
 [0.50209603 0.21646834 0.73708225 0.39717854]]


In [116]:
# 65
import numpy as np
matrix = np.random.random((3, 4))
sorted_matrix_by_column2 = matrix[matrix[:, 1].argsort()]
print(sorted_matrix_by_column2)

[[0.5417364  0.56570206 0.37750811 0.03026486]
 [0.66790723 0.86210197 0.38158099 0.9371422 ]
 [0.69848139 0.8992444  0.32770581 0.65236056]]


In [117]:
# 66
import numpy as np
matrix = np.random.random((3, 3))
determinant = np.linalg.det(matrix)
print(determinant)

-0.5335993010697533


In [118]:
# 67
import numpy as np
arr = np.array([2, 3, 4])
exponentiated_arr = np.exp(arr)
print(exponentiated_arr)

[ 7.3890561  20.08553692 54.59815003]


In [119]:
# 68
import numpy as np
matrix = np.random.random((3, 4))
frobenius_norm = np.linalg.norm(matrix)
print(frobenius_norm)

1.991204004469564


In [121]:
# 69
import numpy as np
matrix = np.arange(9).reshape((3,3))
matrix[matrix==np.max(matrix)] = np.min(matrix)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 0]]


In [122]:
# 70
import numpy as np
matrix1 = np.random.random((3, 4))
matrix2 = np.random.random((4, 5))
matrix_multiplication = np.dot(matrix1, matrix2)
print(matrix_multiplication)

[[1.18376939 0.76627268 1.40816686 0.80121797 1.07908267]
 [1.19868308 0.67887149 1.99353557 0.8678619  0.78902717]
 [0.60859807 0.39123644 0.66740451 0.45089223 0.63643193]]


In [126]:
# 71
import numpy as np
arr = np.array([5, 15, 12, 18, 25])
arr[(10 <= arr) & (arr <= 20)] = 0
print(arr)

[ 5  0  0  0 25]


In [127]:
# 72
import numpy as np
arr = np.array([1, 2, 3, 4])
inverse_sineh_arr = np.arcsinh(arr)
print(inverse_sineh_arr)

[0.88137359 1.44363548 1.81844646 2.09471255]


In [128]:
# 73
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
kronecker_product = np.kron(arr1, arr2)
print(kronecker_product)

[3 4 6 8]


In [129]:
# 74
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean_absolute_deviation = np.mean(np.abs(arr - np.mean(arr)))
print(mean_absolute_deviation)

1.2


In [130]:
# 75
import numpy as np
matrix = np.random.random((3, 3))
matrix[np.triu_indices(3, 1)] = 0
print(matrix)

[[0.7695523  0.         0.        ]
 [0.74312284 0.32016405 0.        ]
 [0.35352923 0.87702507 0.91055328]]


In [131]:
# 76
import numpy as np
arr = np.array([2, 2, 1, 3, 3, 3, 4])
unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts)

Unique values: [1 2 3 4]
Counts: [1 2 3 1]


In [132]:
# 77
import numpy as np
matrix = np.random.random((3, 4))
cumulative_product_axis0 = np.cumprod(matrix, axis=0)
print(cumulative_product_axis0)

[[0.7533718  0.3947452  0.10789098 0.26189694]
 [0.3395801  0.18458904 0.00458046 0.0361528 ]
 [0.12815216 0.0774038  0.00394411 0.03518423]]


In [133]:
# 78
import numpy as np
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [134]:
# 79
import numpy as np
arr = np.array([1, 2, 3])
new_element = 4
arr = np.append(arr, new_element)
print(arr)

[1 2 3 4]


In [135]:
# 80
import numpy as np
arr1 = np.array([3, 7, 1, 10, 4])
arr2 = np.array([2, 5, 8, 1, 7])
absolute_difference = np.abs(arr1 - arr2)
print(absolute_difference)

[1 2 7 9 3]


In [144]:
# 81
import numpy as np
matrix = np.random.random((3, 4))
max_values_indices = np.argmax(matrix, axis=1)
matrix[np.arange(matrix.shape[0]), max_values_indices] = -1
print(matrix)

[[-1.          0.31718264  0.26183487  0.45964582]
 [ 0.71388781 -1.          0.50041282  0.36451952]
 [ 0.45424362 -1.          0.40847443  0.40548893]]


In [145]:
# 82
import numpy as np
matrix = np.random.random((3, 4))
normalized_columns = matrix / np.sum(matrix, axis=0, keepdims=True)
print(normalized_columns)

[[0.02207185 0.39583226 0.15549192 0.45120734]
 [0.6025716  0.18080478 0.45747122 0.4352778 ]
 [0.37535655 0.42336296 0.38703685 0.11351486]]


In [150]:
# 83
import numpy as np
arr = np.array([10, 5, 8, 1, 7])
top_indices = np.argsort(arr)[:2]  # Replace 2 with desired top N
print(top_indices)

[3 1]


In [151]:
# 84
import numpy as np
arr = np.array([1, 2, 3, 4])
string_arr = arr.astype(str)
print(string_arr)

['1' '2' '3' '4']


In [153]:
# 85
import numpy as np
from scipy.stats import percentileofscore
arr = np.array([1, 2, 3, 4, 3])
percentile_rank = np.array([percentileofscore(arr, value) for value in arr])
print(percentile_rank)

[ 20.  40.  70. 100.  70.]


In [154]:
# 86
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 2 4 3 1]


In [155]:
# 87
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
all_nonzero = np.all(arr != 0)
print(all_nonzero)

True


In [156]:
# 88
import numpy as np
matrix = np.random.random((3, 4))
max_indices_per_row = np.argmax(matrix, axis=1)
print(max_indices_per_row)

[0 3 1]


In [157]:
import numpy as np
matrix = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])
nan_mean = np.nanmean(matrix)
matrix[np.isnan(matrix)] = nan_mean
print(matrix)

[[1.         5.28571429 3.        ]
 [4.         5.         5.28571429]
 [7.         8.         9.        ]]


In [158]:
# 90
import numpy as np
matrix = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
row_means_ignore_nan = np.nanmean(matrix, axis=1)
print(row_means_ignore_nan)

[1.5 5.  8. ]


In [159]:
# 91
import numpy as np
matrix = np.random.random((3, 3))
diagonal_sum = np.trace(matrix)
print(diagonal_sum)

1.254756561431603


In [160]:
# 92
import numpy as np
arr_in_radians = np.array([np.pi/2, np.pi, 3*np.pi/2])
arr_in_degrees = np.degrees(arr_in_radians)
print(arr_in_degrees)

[ 90. 180. 270.]


In [161]:
# 93
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
euclidean_distance = np.linalg.norm(arr1 - arr2)
print(euclidean_distance)

5.196152422706632


In [162]:
# 94
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
percentile_25th = np.percentile(arr, 25)
percentile_75th = np.percentile(arr, 75)
arr[(arr >= percentile_25th) & (arr <= percentile_75th)] = 0
print(arr)

[10  0  0  0 50]


In [163]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
squared_difference = (arr1 - arr2)**2
print(squared_difference)

[9 9 9]


In [168]:
# 96
arr = np.arange(8)
arr[arr%2==0] = arr[arr%2==0]+1
print(arr)

[1 1 3 3 5 5 7 7]


In [169]:
# 97
import numpy as np
matrix = np.random.random((3, 4))
normalized_columns_range = (matrix - np.min(matrix, axis=0)) / (np.max(matrix, axis=0) - np.min(matrix, axis=0))
print(normalized_columns_range)

[[1.         1.         1.         1.        ]
 [0.         0.07579925 0.         0.        ]
 [0.32905712 0.         0.03791551 0.72153926]]


In [170]:
# 98
import numpy as np
matrix = np.random.random((3, 4))
cumulative_sum_axis1 = np.cumsum(matrix, axis=1)
print(cumulative_sum_axis1)

[[0.13894425 0.94573806 1.70280259 2.52413006]
 [0.93551625 1.57916779 2.32727826 2.59339522]
 [0.96759559 1.30286516 1.8483839  2.00554797]]


In [171]:
# 99
import numpy as np
arr = np.array([0, 0, 0, 1, 0])
any_nonzero = np.any(arr != 0)
print(any_nonzero)

True


In [172]:
# 100
import numpy as np
matrix = np.random.randint(0, 100, size=(3, 4))
threshold = 75
matrix[matrix > threshold] = threshold
print(matrix)

[[41 75 47 10]
 [75 65 26 75]
 [75 44 26 61]]
