In [1]:
# 1
import pandas as pd
data = pd.read_csv("iris.csv")
print("Shape of the data:")
print(data.shape)
print("\nData Type:")
print(type(data))
print("\nFirst 3 rows:")
print(data.head(3))

Shape of the data:
(150, 5)

Data Type:
<class 'pandas.core.frame.DataFrame'>

First 3 rows:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa


In [1]:
# 2
import pandas as pd
iris_data = pd.read_csv("iris.csv")
print("\nKeys of Iris dataset:")
print(iris_data.keys())
print("\nNumber of rows and columns of Iris dataset:")
print(iris_data.shape) 


Keys of Iris dataset:
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

Number of rows and columns of Iris dataset:
(150, 5)


In [3]:
# 3
import pandas as pd
iris = pd.read_csv("iris.csv")
print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [4]:
# 4
import numpy as np
from scipy import sparse
eye = np.eye(4)
print("NumPy array:\n", eye)
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)

NumPy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [5]:
# 5
import pandas as pd
data = pd.read_csv("iris.csv")
print(data.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [7]:
# 6
import pandas as pd
data = pd.read_csv("iris.csv")
print("Observations of each species:")
print(data['species'].value_counts()) 

Observations of each species:
species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64


In [11]:
# 7
import pandas as pd
data = pd.read_csv("iris.csv")
print("Original Data:")
print(data.head(5))
new_data = data.drop('sepal_length',axis=1)
print("After removing id column:")
print(new_data.head(5)) 

Original Data:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
After removing id column:
   sepal_width  petal_length  petal_width      species
0          3.5           1.4          0.2  Iris-setosa
1          3.0           1.4          0.2  Iris-setosa
2          3.2           1.3          0.2  Iris-setosa
3          3.1           1.5          0.2  Iris-setosa
4          3.6           1.4          0.2  Iris-setosa


In [16]:
# 8
import pandas as pd
data = pd.read_csv('iris.csv')
print("Original data:")
print(data.head())
x = data.iloc[:, [1,2,3,4]].values
print("Dataframe :\n",x)

Original data:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
Dataframe :
 [[3.5 1.4 0.2 'Iris-setosa']
 [3.0 1.4 0.2 'Iris-setosa']
 [3.2 1.3 0.2 'Iris-setosa']
 [3.1 1.5 0.2 'Iris-setosa']
 [3.6 1.4 0.2 'Iris-setosa']
 [3.9 1.7 0.4 'Iris-setosa']
 [3.4 1.4 0.3 'Iris-setosa']
 [3.4 1.5 0.2 'Iris-setosa']
 [2.9 1.4 0.2 'Iris-setosa']
 [3.1 1.5 0.1 'Iris-setosa']
 [3.7 1.5 0.2 'Iris-setosa']
 [3.4 1.6 0.2 'Iris-setosa']
 [3.0 1.4 0.1 'Iris-setosa']
 [3.0 1.1 0.1 'Iris-setosa']
 [4.0 1.2 0.2 'Iris-setosa']
 [4.4 1.5 0.4 'Iris-setosa']
 [3.9 1.3 0.4 'Iris-setosa']
 [3.5 1.4 0.3 'Iris-setosa']
 [3.8 1.7 0.3 'Iris-setosa']
 [3.8 1